### ISSUE TITLE
rock-display does not work on the rc

### ISSUE THREAD

**Issue by goldhoorn** [rock-core/gui-vizkit#29]
```
[11:12:03 goldhoorn bin]$ rock-display 
/home/goldhoorn/bootstraps/rc/tools/utilrb/lib/utilrb/pkgconfig.rb:461: warning: Insecure world writable dir /opt/Xilinx/SDK/2013.4 in PATH, mode 040777
/usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- rock/bundle (LoadError)
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/goldhoorn/bootstraps/rc/gui/vizkit/bin/rock-display:5:in `<main>'

```

If there are dependancies missing, they are not in the manifests...

**Comment by goldhoorn** [comment]
Created a PR #31 and #30  for this,
but still got on rc this error:

```
Vizkit[WARN]: Cannot load vizkit extension /home/goldhoorn/bootstraps/rc/install/lib/qt/designer/widgets/base_vizkit.rb
Vizkit[WARN]: undefined method `master_project' for Orocos:Module
Vizkit[WARN]: /home/goldhoorn/bootstraps/rc/gui/vizkit/lib/vizkit/plugin.rb:110:in `classes'
Vizkit[WARN]: /home/goldhoorn/bootstraps/rc/gui/vizkit/lib/vizkit/plugin.rb:73:in `normalize_obj'
Vizkit[WARN]: /home/goldhoorn/bootstraps/rc/gui/vizkit/lib/vizkit/plugin.rb:75:in `normalize_obj'
Vizkit[WARN]: /home/goldhoorn/bootstraps/rc/gui/vizkit/lib/vizkit/uiloader.rb:401:in `find_plugin_spec!'
Vizkit[WARN]: /home/goldhoorn/bootstraps/rc/gui/vizkit/lib/vizkit/uiloader.rb:230:in `block in register_plugin_for'
Vizkit[WARN]: /home/goldhoorn/bootstraps/rc/gui/vizkit/lib/vizkit/uiloader.rb:229:in `each'
Vizkit[WARN]: /home/goldhoorn/bootstraps/rc/gui/vizkit/lib/vizkit/uiloader.rb:229:in `register_plugin_for'
Vizkit[WARN]: /home/goldhoorn/bootstraps/rc/gui/vizkit/lib/vizkit/uiloader.rb:66:in `register_plugin_for'
Vizkit[WARN]: /home/goldhoorn/bootstraps/rc/gui/vizkit/lib/vizkit/uiloader.rb:84:in `register_3d_plugin_for'
Vizkit[WARN]: /home/goldhoorn/bootstraps/rc/install/lib/qt/designer/widgets/base_vizkit.rb:2:in `<top (required)>'
Vizkit[WARN]: /home/goldhoorn/bootstraps/rc/gui/vizkit/lib/vizkit/uiloader.rb:139:in `load'
Vizkit[WARN]: /home/goldhoorn/bootstraps/rc/gui/vizkit/lib/vizkit/uiloader.rb:139:in `block in load_extensions'
Vizkit[WARN]: /home/goldhoorn/bootstraps/rc/gui/vizkit/lib/vizkit/uiloader.rb:134:in `each'
Vizkit[WARN]: /home/goldhoorn/bootstraps/rc/gui/vizkit/lib/vizkit/uiloader.rb:134:in `load_extensions'
Vizkit[WARN]: /home/goldhoorn/bootstraps/rc/gui/vizkit/lib/vizkit/uiloader.rb:150:in `block in load_extensions'
Vizkit[WARN]: /home/goldhoorn/bootstraps/rc/gui/vizkit/lib/vizkit/uiloader.rb:134:in `each'
Vizkit[WARN]: /home/goldhoorn/bootstraps/rc/gui/vizkit/lib/vizkit/uiloader.rb:134:in `load_extensions'
Vizkit[WARN]: /home/goldhoorn/bootstraps/rc/gui/vizkit/lib/vizkit/uiloader.rb:119:in `block in initialize'
Vizkit[WARN]: /home/goldhoorn/bootstraps/rc/gui/vizkit/lib/vizkit/uiloader.rb:116:in `each'
Vizkit[WARN]: /home/goldhoorn/bootstraps/rc/gui/vizkit/lib/vizkit/uiloader.rb:116:in `initialize'
Vizkit[WARN]: /home/goldhoorn/bootstraps/rc/gui/vizkit/lib/vizkit/vizkit.rb:47:in `new'
Vizkit[WARN]: /home/goldhoorn/bootstraps/rc/gui/vizkit/lib/vizkit/vizkit.rb:47:in `default_loader'
Vizkit[WARN]: /home/goldhoorn/bootstraps/rc/gui/vizkit/bin/rock-display:76:in `<main>'
```

Same repeats for each plugin

**Comment by doudou** [comment]
Yes, I would have like to have @D-Alex have a look at what should go in the release ... Guess we'll have to take care of it.

**Comment by D-Alex** [comment]
Solved. The remaining question is if vizikit shout depend on base/scripts (#30)
