### ISSUE TITLE
RC: problems with sample initialization

### ISSUE THREAD

**Issue by goldhoorn** [rock-core/gui-vizkit#33]
I traced the problem from issues

https://github.com/rock-core/base-types/pull/45
https://github.com/rock-core/base-types/pull/8

 down to the vizkit-items and the handling of vizkit.

For bug 8 (zero dimension) it helps to remove this line: https://github.com/rock-core/gui-vizkit/blob/master/lib/vizkit/vizkit_items.rb#L515 the line causes a zero sample to be created which is invalid for a spline. 

This fixed 8 but then triggers bug 45 (even i don't know if no initialization helps at all).

At the bottom of this msg i posted a working and non-working codeflow, both occurs during normal run when the spline is fixed as mentioned in bug 45.

Woking
```
Hallo 2: Float
/home/goldhoorn/bootstraps/release/install/lib/ruby/2.1.0/typelib.rb:209:in `to_ruby'
/home/goldhoorn/bootstraps/release/install/lib/ruby/2.1.0/typelib/compound_type.rb:451:in `get'
/home/goldhoorn/bootstraps/release/install/lib/ruby/2.1.0/typelib/compound_type.rb:187:in `block (3 levels) in custom_convertion_module'
/home/goldhoorn/bootstraps/release/tools/orocos.rb/lib/orocos/async/task_context_proxy.rb:300:in `block in on_data'
/home/goldhoorn/bootstraps/release/tools/orocos.rb/lib/orocos/async/object_base.rb:51:in `call'
/home/goldhoorn/bootstraps/release/tools/orocos.rb/lib/orocos/async/object_base.rb:51:in `call'
/home/goldhoorn/bootstraps/release/tools/orocos.rb/lib/orocos/async/object_base.rb:394:in `block in process_event'
/home/goldhoorn/bootstraps/release/tools/orocos.rb/lib/orocos/async/object_base.rb:393:in `each'
/home/goldhoorn/bootstraps/release/tools/orocos.rb/lib/orocos/async/object_base.rb:393:in `process_event'
/home/goldhoorn/bootstraps/release/tools/orocos.rb/lib/orocos/async/task_context_proxy.rb:328:in `process_event'
/home/goldhoorn/bootstraps/release/tools/orocos.rb/lib/orocos/async/object_base.rb:254:in `block (2 levels) in proxy_event'
/home/goldhoorn/bootstraps/release/tools/orocos.rb/lib/orocos/async/object_base.rb:51:in `call'
/home/goldhoorn/bootstraps/release/tools/orocos.rb/lib/orocos/async/object_base.rb:51:in `call'
/home/goldhoorn/bootstraps/release/tools/orocos.rb/lib/orocos/async/object_base.rb:394:in `block in process_event'
/home/goldhoorn/bootstraps/release/tools/orocos.rb/lib/orocos/async/object_base.rb:393:in `each'
/home/goldhoorn/bootstraps/release/tools/orocos.rb/lib/orocos/async/object_base.rb:393:in `process_event'
/home/goldhoorn/bootstraps/release/tools/orocos.rb/lib/orocos/async/object_base.rb:254:in `block (2 levels) in proxy_event'
/home/goldhoorn/bootstraps/release/tools/orocos.rb/lib/orocos/async/object_base.rb:51:in `call'
/home/goldhoorn/bootstraps/release/tools/orocos.rb/lib/orocos/async/object_base.rb:51:in `call'
/home/goldhoorn/bootstraps/release/tools/orocos.rb/lib/orocos/async/object_base.rb:394:in `block in process_event'
/home/goldhoorn/bootstraps/release/tools/orocos.rb/lib/orocos/async/object_base.rb:393:in `each'
/home/goldhoorn/bootstraps/release/tools/orocos.rb/lib/orocos/async/object_base.rb:393:in `process_event'
/home/goldhoorn/bootstraps/release/tools/orocos.rb/lib/orocos/async/object_base.rb:338:in `block in event'
/home/goldhoorn/bootstraps/release/tools/utilrb/lib/utilrb/event_loop.rb:158:in `call'
/home/goldhoorn/bootstraps/release/tools/utilrb/lib/utilrb/event_loop.rb:158:in `call'
/home/goldhoorn/bootstraps/release/tools/utilrb/lib/utilrb/event_loop.rb:615:in `block in step'
/home/goldhoorn/bootstraps/release/tools/utilrb/lib/utilrb/event_loop.rb:704:in `call'
/home/goldhoorn/bootstraps/release/tools/utilrb/lib/utilrb/event_loop.rb:704:in `handle_errors'
/home/goldhoorn/bootstraps/release/tools/utilrb/lib/utilrb/event_loop.rb:615:in `step'
/usr/lib/ruby/2.1.0/forwardable.rb:183:in `step'
/home/goldhoorn/bootstraps/release/gui/vizkit/lib/vizkit/vizkit.rb:133:in `block in exec'
/usr/lib/ruby/vendor_ruby/2.1.0/Qt/qtruby4.rb:2427:in `call'
/usr/lib/ruby/vendor_ruby/2.1.0/Qt/qtruby4.rb:2427:in `invoke'
/usr/lib/ruby/vendor_ruby/2.1.0/Qt/qtruby4.rb:469:in `qt_metacall'
/usr/lib/ruby/vendor_ruby/2.1.0/Qt/qtruby4.rb:469:in `method_missing'
/usr/lib/ruby/vendor_ruby/2.1.0/Qt/qtruby4.rb:469:in `exec'
/home/goldhoorn/bootstraps/release/gui/vizkit/lib/vizkit/vizkit.rb:137:in `exec'
start.rb:18:in `block in <main>'
/home/goldhoorn/bootstraps/release/tools/orocos.rb/lib/orocos/process.rb:695:in `block in run'
/home/goldhoorn/bootstraps/release/tools/orocos.rb/lib/orocos/process.rb:1098:in `guard'
/home/goldhoorn/bootstraps/release/tools/orocos.rb/lib/orocos/process.rb:694:in `run'
/home/goldhoorn/bootstraps/release/tools/orocos.rb/lib/orocos/process.rb:107:in `run'
start.rb:7:in `<main>'

```

Nonworking:
```
Hallo 2: #<Typelib::NumericType: /double>
/home/goldhoorn/bootstraps/release/install/lib/ruby/2.1.0/typelib.rb:209:in `to_ruby'
/home/goldhoorn/bootstraps/release/install/lib/ruby/2.1.0/typelib/type.rb:683:in `to_ruby'
/home/goldhoorn/bootstraps/release/gui/vizkit/lib/vizkit/vizkit_items.rb:301:in `update'
/home/goldhoorn/bootstraps/release/gui/vizkit/lib/vizkit/vizkit_items.rb:188:in `initialize'
/home/goldhoorn/bootstraps/release/gui/vizkit/lib/vizkit/vizkit_items.rb:361:in `new'
/home/goldhoorn/bootstraps/release/gui/vizkit/lib/vizkit/vizkit_items.rb:361:in `block in update'
/home/goldhoorn/bootstraps/release/gui/vizkit/lib/vizkit/vizkit_items.rb:351:in `upto'
/home/goldhoorn/bootstraps/release/gui/vizkit/lib/vizkit/vizkit_items.rb:351:in `update'
/home/goldhoorn/bootstraps/release/gui/vizkit/lib/vizkit/vizkit_items.rb:592:in `block in initialize'
/home/goldhoorn/bootstraps/release/tools/orocos.rb/lib/orocos/async/task_context_proxy.rb:305:in `block in on_data'
/home/goldhoorn/bootstraps/release/tools/orocos.rb/lib/orocos/async/object_base.rb:51:in `call'
/home/goldhoorn/bootstraps/release/tools/orocos.rb/lib/orocos/async/object_base.rb:51:in `call'
/home/goldhoorn/bootstraps/release/tools/orocos.rb/lib/orocos/async/object_base.rb:394:in `block in process_event'
/home/goldhoorn/bootstraps/release/tools/orocos.rb/lib/orocos/async/object_base.rb:393:in `each'
/home/goldhoorn/bootstraps/release/tools/orocos.rb/lib/orocos/async/object_base.rb:393:in `process_event'
/home/goldhoorn/bootstraps/release/tools/orocos.rb/lib/orocos/async/task_context_proxy.rb:328:in `process_event'
/home/goldhoorn/bootstraps/release/tools/orocos.rb/lib/orocos/async/object_base.rb:254:in `block (2 levels) in proxy_event'
/home/goldhoorn/bootstraps/release/tools/orocos.rb/lib/orocos/async/object_base.rb:51:in `call'
/home/goldhoorn/bootstraps/release/tools/orocos.rb/lib/orocos/async/object_base.rb:51:in `call'
/home/goldhoorn/bootstraps/release/tools/orocos.rb/lib/orocos/async/object_base.rb:394:in `block in process_event'
/home/goldhoorn/bootstraps/release/tools/orocos.rb/lib/orocos/async/object_base.rb:393:in `each'
/home/goldhoorn/bootstraps/release/tools/orocos.rb/lib/orocos/async/object_base.rb:393:in `process_event'
/home/goldhoorn/bootstraps/release/tools/orocos.rb/lib/orocos/async/object_base.rb:254:in `block (2 levels) in proxy_event'
/home/goldhoorn/bootstraps/release/tools/orocos.rb/lib/orocos/async/object_base.rb:51:in `call'
/home/goldhoorn/bootstraps/release/tools/orocos.rb/lib/orocos/async/object_base.rb:51:in `call'
/home/goldhoorn/bootstraps/release/tools/orocos.rb/lib/orocos/async/object_base.rb:394:in `block in process_event'
/home/goldhoorn/bootstraps/release/tools/orocos.rb/lib/orocos/async/object_base.rb:393:in `each'
/home/goldhoorn/bootstraps/release/tools/orocos.rb/lib/orocos/async/object_base.rb:393:in `process_event'
/home/goldhoorn/bootstraps/release/tools/orocos.rb/lib/orocos/async/object_base.rb:338:in `block in event'
/home/goldhoorn/bootstraps/release/tools/utilrb/lib/utilrb/event_loop.rb:158:in `call'
/home/goldhoorn/bootstraps/release/tools/utilrb/lib/utilrb/event_loop.rb:158:in `call'
/home/goldhoorn/bootstraps/release/tools/utilrb/lib/utilrb/event_loop.rb:615:in `block in step'
/home/goldhoorn/bootstraps/release/tools/utilrb/lib/utilrb/event_loop.rb:704:in `call'
/home/goldhoorn/bootstraps/release/tools/utilrb/lib/utilrb/event_loop.rb:704:in `handle_errors'
/home/goldhoorn/bootstraps/release/tools/utilrb/lib/utilrb/event_loop.rb:615:in `step'
/usr/lib/ruby/2.1.0/forwardable.rb:183:in `step'
/home/goldhoorn/bootstraps/release/gui/vizkit/lib/vizkit/vizkit.rb:133:in `block in exec'
/usr/lib/ruby/vendor_ruby/2.1.0/Qt/qtruby4.rb:2427:in `call'
/usr/lib/ruby/vendor_ruby/2.1.0/Qt/qtruby4.rb:2427:in `invoke'
/usr/lib/ruby/vendor_ruby/2.1.0/Qt/qtruby4.rb:469:in `qt_metacall'
/usr/lib/ruby/vendor_ruby/2.1.0/Qt/qtruby4.rb:469:in `method_missing'
/usr/lib/ruby/vendor_ruby/2.1.0/Qt/qtruby4.rb:469:in `exec'
/home/goldhoorn/bootstraps/release/gui/vizkit/lib/vizkit/vizkit.rb:137:in `exec'
start.rb:18:in `block in <main>'
/home/goldhoorn/bootstraps/release/tools/orocos.rb/lib/orocos/process.rb:695:in `block in run'
/home/goldhoorn/bootstraps/release/tools/orocos.rb/lib/orocos/process.rb:1098:in `guard'
/home/goldhoorn/bootstraps/release/tools/orocos.rb/lib/orocos/process.rb:694:in `run'
/home/goldhoorn/bootstraps/release/tools/orocos.rb/lib/orocos/process.rb:107:in `run'
start.rb:7:in `<main>'

```

This is definetly for @D-Alex

**Comment by goldhoorn** [comment]
@D-Alex : if you have in near time no resources available, or the code need to be refractored in larger scale, i vote to apply the 2 PRs as workaround, and keep this as issue.

By doing so the release can be released and we working for the right solution for the next release. This would be acceptable for me since spline seems the only datatype which is affected so far.

**Comment by doudou** [comment]
The type returned by #to_ruby is available is type.convertion_to_ruby[0]. One could change https://github.com/rock-core/gui-vizkit/blob/master/lib/vizkit/vizkit_items.rb#L291 to

```
if @typelib_val.class.needs_convertion_to_ruby?
   ruby_type = @typelib_val.class.convertion_to_ruby[0]
   @direct_type = DIRECTLY_DISPLAYED_RUBY_TYPES.any? { |rt| rt === rb_sample }
else
   @direct_type = false
end
```

to determine whether vizkit is supposed to use the ruby type or not for the display. This would avoid the unnecessary conversion.

**Comment by goldhoorn** [comment]
On 07.05.2015 16:44, Sylvain Joyeux wrote:
>
> The type returned by #to_ruby is available is 
> type.convertion_to_ruby[0]. One could change 
> https://github.com/rock-core/gui-vizkit/blob/master/lib/vizkit/vizkit_items.rb#L291 
> to
>
> |if @typelib_val.class.needs_convertion_to_ruby?
>     ruby_type = @typelib_val.class.convertion_to_ruby[0]
>     @direct_type = DIRECTLY_DISPLAYED_RUBY_TYPES.any? { |rt| rt === rb_sample }
> else
>     @direct_type = false
> end
> |
>
> to determine whether vizkit is supposed to use the ruby type or not 
> for the display. This would avoid the unnecessary conversion.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/rock-core/gui-vizkit/issues/33#issuecomment-99894135>.
>
It behaves better but:

There is a bug in your comment it must be two ==

By doing so, the system behaves besser, but no atomic values get 
displaed anmyore. The task inspectors shows only /int32 for the time 
instead of the value.


-- 
  Dipl.-Inf. Matthias Goldhoorn
  Space and Underwater Robotic

  Universität Bremen
  FB 3 - Mathematik und Informatik
  AG Robotik
  Robert-Hooke-Straße 1
  28359 Bremen, Germany
  
  Zentrale: +49 421 178 45-6611
  
  Besuchsadresse der Nebengeschäftstelle:
  Robert-Hooke-Straße 5
  28359 Bremen, Germany
  
  Tel.:    +49 421 178 45-4193
  Empfang: +49 421 178 45-6600
  Fax:     +49 421 178 45-4150
  E-Mail:  matthias.goldhoorn@informatik.uni-bremen.de

  Weitere Informationen: http://www.informatik.uni-bremen.de/robotik

**Comment by doudou** [comment]
Obvious bugs:
 - the any? test should be DIRECTLY_DISPLAYED_RUBY_TYPES.include?(ruby_type)
 - don't forget to remove the assignation of rb_sample ...

**Comment by goldhoorn** [comment]
it is fixed on master and the release finally
